version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - web
    restart: always

  web:
    build: ./backend 
    ports:
      - "5001:5000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    restart: always
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
networks:
  default:
    driver: bridge 